include $(HOME)/Classes/StatComputing/IDynDocs/inst/Make/Makefile


#DB2_XSL=../XSL/db2tex.xsl
#%.tex: %.xml $(DB2_XSL)
#	xsltproc  --stringparam latex.documentclass article $(DB2_XSL) $< > $@
#
%.pdf: %.tex
	pdflatex $*

